### ISSUE TITLE
Have you thought about trying to make the badges persist after you close and reopen vscode?

### ISSUE THREAD

**Issue by EvsWorld** [MadTiago/vscode-file-badge#1]
First i wanted to say thanks for making this; i was looking for exactly this.

I haven't dabbled in working on vscode extensions yet but i put a todo to give it a try making these badges persistent. I will give it a shot myself as soon as I get a chance. Let me know if you have any ideas.

**Comment by MadTiago** [comment]
Thanks for the kind message!
I also thought about doing it at the start, but was still learning how to make an extension, and didn't dive too deep into it.
Got some time in and it now persists across sessions, try it out!
